Homework 2
================
Ruichen Yang
2026-10-07

## Problem 1

``` r
subway_df = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  show_col_types = FALSE
) |>
  clean_names() |>
  select(
    line,
    station_name,
    station_latitude,
    station_longitude,
    route1:route11,
    entrance_type,
    entry,
    vending,
    ada
  ) |>
  mutate(
  entry = entry == "YES"
)
```

The cleaned subway dataset contains 1868 observations and 19 variables.
It includes station name and line, station latitude and longitude,
routes served, entrance type, entry permission, vending status, and ADA
compliance. I cleaned the data by standardizing variable names,
selecting the requested variables, and converting the entry variable
from YES/NO to a logical variable. These data are not fully tidy because
the routes served are stored across multiple columns (`route1` through
`route11`) rather than in a single route variable.

``` r
station_count = subway_df |>
  distinct(line, station_name) |>
  nrow()

station_count
```

    ## [1] 465

``` r
ada_station_count = subway_df |>
  filter(ada) |>
  distinct(line, station_name) |>
  nrow()

ada_station_count
```

    ## [1] 84

``` r
entry_prop_no_vending = subway_df |>
  filter(vending == "NO") |>
  summarize(
    proportion = mean(entry)
  ) |>
  pull(proportion)

entry_prop_no_vending
```

    ## [1] 0.3770492

``` r
subway_long = subway_df |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name",
    values_transform = list(route_name = as.character),
    values_drop_na = TRUE
  ) |>
  mutate(
    route_number = as.integer(route_number)
  )

head(subway_long)
```

    ## # A tibble: 6 × 10
    ##   line     station_name station_latitude station_longitude entrance_type entry
    ##   <chr>    <chr>                   <dbl>             <dbl> <chr>         <lgl>
    ## 1 4 Avenue 25th St                  40.7             -74.0 Stair         TRUE 
    ## 2 4 Avenue 25th St                  40.7             -74.0 Stair         TRUE 
    ## 3 4 Avenue 36th St                  40.7             -74.0 Stair         TRUE 
    ## 4 4 Avenue 36th St                  40.7             -74.0 Stair         TRUE 
    ## 5 4 Avenue 36th St                  40.7             -74.0 Stair         TRUE 
    ## 6 4 Avenue 36th St                  40.7             -74.0 Stair         TRUE 
    ## # ℹ 4 more variables: vending <chr>, ada <lgl>, route_number <int>,
    ## #   route_name <chr>

``` r
a_train_station_count = subway_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()

a_train_station_count
```

    ## [1] 60

``` r
a_train_ada_count = subway_long |>
  filter(route_name == "A", ada) |>
  distinct(line, station_name) |>
  nrow()

a_train_ada_count
```

    ## [1] 17

There are 465 distinct subway stations in the dataset, where stations
are identified by both line and station name. Of these, 84 stations are
ADA compliant. Among station entrances and exits without vending,
approximately 37.7% allow entrance.

After reorganizing the route variables into a tidy format, there are 60
distinct stations that serve the A train. Of these stations, 17 are ADA
compliant.

## Problem 2

``` r
excel_sheets("data/202610 Trash Wheel Collection Data.xlsx")
```

    ## [1] "Mr. Trash Wheel"                 "Professor Trash Wheel"          
    ## [3] "Captain Trash Wheel"             "Gwynnda the Good Wheel of the W"
    ## [5] "Sampling Methodology"            "Homes powered note"

``` r
mr_trash = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N743"
) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    sports_balls = as.integer(round(sports_balls)),
    trash_wheel = "Mr. Trash Wheel"
  )

dim(mr_trash)
```

    ## [1] 740  15

``` r
professor_trash = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Professor Trash Wheel",
  range = "A2:M140"
) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    plastic_bottles = na_if(as.character(plastic_bottles), "dive"),
    plastic_bottles = as.numeric(plastic_bottles),
    trash_wheel = "Professor Trash Wheel"
  )

dim(professor_trash)
```

    ## [1] 137  14

``` r
gwynnda_trash = read_excel(
  "data/202610 Trash Wheel Collection Data.xlsx",
  sheet = "Gwynnda the Good Wheel of the W",
  range = cell_limits(c(2, 1), c(NA, 12))
) |>
  clean_names() |>
  filter(!is.na(dumpster)) |>
  mutate(
    trash_wheel = "Gwynnda"
  )

dim(gwynnda_trash)
```

    ## [1] 392  13

``` r
trash_wheel_df = bind_rows(
  mr_trash |> mutate(year = as.integer(year)),
  professor_trash |> mutate(year = as.integer(year)),
  gwynnda_trash |> mutate(year = as.integer(year))
)

dim(trash_wheel_df)
```

    ## [1] 1269   15

``` r
professor_total_weight = trash_wheel_df |>
  filter(trash_wheel == "Professor Trash Wheel") |>
  summarize(
    total_weight = sum(weight_tons, na.rm = TRUE)
  ) |>
  pull(total_weight)

professor_total_weight
```

    ## [1] 294.96

``` r
gwynnda_cigarette_butts = trash_wheel_df |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  ) |>
  summarize(
    total_butts = sum(cigarette_butts, na.rm = TRUE)
  ) |>
  pull(total_butts)

gwynnda_cigarette_butts
```

    ## [1] 18120

The combined Trash Wheel dataset contains 1269 observations and 15
variables. The data include information on the date of each dumpster
collection, weight and volume of trash collected, counts of different
types of litter such as plastic bottles, polystyrene, cigarette butts,
glass bottles, plastic bags, wrappers, and sports balls, as well as the
Trash Wheel responsible for each collection. I imported and cleaned the
three Trash Wheel datasets separately, removed non-data rows,
standardized variable names and types, and then combined them into a
single tidy dataset.

For the available data, Professor Trash Wheel collected a total of
294.96 tons of trash. Gwynnda collected 18,120 cigarette butts in June
2022.

## Problem 3

``` r
mci_baseline = read_csv(
  "data/MCI_baseline.csv",
  skip = 1,
  na = "."
) |>
  clean_names() |>
  mutate(
    sex = factor(
      sex,
      levels = c(0, 1),
      labels = c("Female", "Male")
    ),
    apoe4 = factor(
      apoe4,
      levels = c(0, 1),
      labels = c("Non-carrier", "Carrier")
    )
  ) |>
  filter(
    is.na(age_at_onset) | age_at_onset > current_age
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
dim(mci_baseline)
```

    ## [1] 479   6

``` r
baseline_summary = mci_baseline |>
  summarize(
    participants = n(),
    developed_mci = sum(!is.na(age_at_onset)),
    mean_baseline_age = mean(current_age),
    prop_women_apoe4 = mean(apoe4[sex == "Female"] == "Carrier")
  )

baseline_summary
```

    ## # A tibble: 1 × 4
    ##   participants developed_mci mean_baseline_age prop_women_apoe4
    ##          <int>         <int>             <dbl>            <dbl>
    ## 1          479            93              65.0              0.3

The baseline dataset initially contained 483 participants. I skipped the
non-data first row during import, treated “.” as missing values, cleaned
the variable names, and encoded sex and APOE4 carrier status as
categorical variables rather than numeric variables. I then removed
participants who already had MCI at baseline, leaving 479 eligible
participants.

Among these participants, 93 developed MCI during follow-up. The average
baseline age was 65.03 years. Among women in the study, 30% were APOE4
carriers.

``` r
amyloid_raw = read_csv(
  "data/mci_amyloid.csv",
  skip = 1,
  na = c(".", "NA", "Na"),
  show_col_types = FALSE
) |>
  clean_names()
```

``` r
amyloid_long = amyloid_raw |>
  pivot_longer(
    cols = baseline:time_8,
    names_to = "visit",
    values_to = "amyloid_ratio"
  ) |>
  mutate(
    time_years = recode(
      visit,
      "baseline" = 0,
      "time_2" = 2,
      "time_4" = 4,
      "time_6" = 6,
      "time_8" = 8
    ),
    amyloid_ratio = as.numeric(amyloid_ratio)
  )

dim(amyloid_long)
```

    ## [1] 2435    4

``` r
head(amyloid_long)
```

    ## # A tibble: 6 × 4
    ##   study_id visit    amyloid_ratio time_years
    ##      <dbl> <chr>            <dbl>      <dbl>
    ## 1        1 baseline         0.111          0
    ## 2        1 time_2          NA              2
    ## 3        1 time_4           0.109          4
    ## 4        1 time_6           0.105          6
    ## 5        1 time_8           0.107          8
    ## 6        2 baseline         0.107          0

``` r
baseline_only = mci_baseline |>
  select(id) |>
  anti_join(
    amyloid_raw |> select(study_id),
    by = c("id" = "study_id")
  )

amyloid_only = amyloid_raw |>
  select(study_id) |>
  anti_join(
    mci_baseline |> select(id),
    by = c("study_id" = "id")
  )

baseline_only
```

    ## # A tibble: 8 × 1
    ##      id
    ##   <dbl>
    ## 1    14
    ## 2    49
    ## 3    92
    ## 4   179
    ## 5   268
    ## 6   304
    ## 7   389
    ## 8   412

``` r
amyloid_only
```

    ## # A tibble: 16 × 1
    ##    study_id
    ##       <dbl>
    ##  1       72
    ##  2      234
    ##  3      283
    ##  4      380
    ##  5      484
    ##  6      485
    ##  7      486
    ##  8      487
    ##  9      488
    ## 10      489
    ## 11      490
    ## 12      491
    ## 13      492
    ## 14      493
    ## 15      494
    ## 16      495

``` r
mci_combined = mci_baseline |>
  inner_join(
    amyloid_long,
    by = c("id" = "study_id")
  ) |>
  arrange(id, time_years)

dim(mci_combined)
```

    ## [1] 2355    9

``` r
mci_combined |>
  distinct(id) |>
  nrow()
```

    ## [1] 471

``` r
write_csv(
  mci_combined,
  "data/mci_combined.csv"
)
```

The amyloid dataset initially contained 487 participants, with amyloid
biomarker measurements recorded at baseline and at approximately 2, 4,
6, and 8 years of follow-up. I skipped the non-data first row during
import, treated the dataset’s missing-value codes as missing values,
cleaned the variable names, and reshaped the repeated biomarker
measurements from wide to long format. The resulting long-format dataset
contains one row for each participant-visit combination, with separate
variables for the visit, time since baseline, and amyloid ratio.

There were 8 participants who appeared only in the baseline dataset and
16 participants who appeared only in the amyloid dataset. After
retaining only participants present in both datasets, the combined
dataset contains 471 unique participants, 2,355 observations, and 9
variables. The combined dataset includes baseline demographic and MCI
information together with longitudinal amyloid measurements. The final
dataset was exported as `data/mci_combined.csv`.
